Repository Moonsong-Labs/storage-hub, pull requests merged in 2024-03, with the labels that each got.

#15 feat: ✨ BSP stop storing functionality and hooking up pallets in runtime
  Cargo.lock
  Cargo.toml
  pallets/file-system/Cargo.toml
  pallets/file-system/src/benchmarking.rs
  pallets/file-system/src/lib.rs
  pallets/file-system/src/mock.rs
  pallets/file-system/src/tests.rs
  pallets/file-system/src/types.rs
  pallets/file-system/src/utils.rs
  pallets/proofs-dealer/Cargo.toml
  pallets/proofs-dealer/src/lib.rs
  pallets/providers/Cargo.toml
  pallets/providers/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement, runtime

#19 chore: add all common dependencies to workspace
  Cargo.lock
  Cargo.toml
  pallets/file-system/Cargo.toml
  pallets/proofs-dealer/Cargo.toml
  pallets/providers/Cargo.toml
  support/traits/Cargo.toml
Labels: runtime, chore

#25 feat(CI): :rocket: Integrated DockerHub to CI workflow
  .github/workflows/build.yml
  .github/workflows/parachain.yml
  bun.lockb
  docker/latest-node-compose.yml
  docker/local-node-compose.yml
  docker/storage-hub-node-compose.yml
  docker/storage-hub-node.Dockerfile
  rust-toolchain
  test/README.md
  test/configs/simple.toml
  test/configs/simple.zndsl
  test/package.json
Labels: enhancement
